import ArrowBack from '@material-ui/icons/ArrowBack';
import ArrowBackIos from '@material-ui/icons/ArrowBackIos';
import ArrowForward from '@material-ui/icons/ArrowForward';
import CheckCircle from '@material-ui/icons/CheckCircle';
import CheckCircleOutlined from '@material-ui/icons/CheckCircleOutlined';
import Close from '@material-ui/icons/Close';
import Cloud from '@material-ui/icons/Cloud';
import CloudQueue from '@material-ui/icons/CloudQueue';
import Home from '@material-ui/icons/Home';
import MoreVert from '@material-ui/icons/MoreVert';
import Person from '@material-ui/icons/Person';
import PlayCircleOutline from '@material-ui/icons/PlayCircleOutline';
import Portrait from '@material-ui/icons/Portrait';
import Public from '@material-ui/icons/Public';
import Refresh from '@material-ui/icons/Refresh';
import Search from '@material-ui/icons/Search';
export const icons = {ArrowBack, ArrowBackIos, ArrowForward, CheckCircle, CheckCircleOutlined, Close, Cloud, CloudQueue, Home, MoreVert, Person, PlayCircleOutline, Portrait, Public, Refresh, Search};
