export const language = {
  sessionIconNextChapter: 'Next Chapter',
  sessionIconPreviousChapter: 'Previous Chapter',
  sessionIconSettings: 'Settings',
  sessionSettings: 'Settings',
  sessionSettingsControl: 'Ok',
  sessionSettingsPageSize: 'Page Size',
  sessionSettingsPageSizeNone: 'NO SCALING',
  sessionSettingsPageSizePaperback: 'FORCE PAPERBACK SIZE',
  sessionSettingsPageSizeDigest: 'FORCE DIGEST SIZE',
  sessionSettingsPageSizePocket: 'FORCE POCKET SIZE',
  sessionSettingsPageSizeJapaneseB6: 'FORCE B6 SIZE',
  sessionSettingsPageSizeISOA5: 'FORCE A5 SIZE',
  sessionToastNextActive: 'Going to the next chapter!',
  sessionToastNextRepeat: 'Open the next chapter?',
  sessionToastNextUnavailable: 'No next chapter available.',
  sessionToastPreviousActive: 'Going to the previous chapter!',
  sessionToastPreviousRepeat: 'Open the previous chapter?',
  sessionToastPreviousUnavailable: 'No previous chapter available.'
};
