export const language = {
  basicDisconnectBody: 'Are you sure you wish to disconnect from the server?',
  basicDisconnectButtons: ['Yes', 'No'],
  basicErrorBody: 'Oops! The server could not be reached or returned an error. Check your device and server connectivity, and then try again.',
  basicErrorButtons: ['Cancel', 'Retry'],
  connect: 'Connect',
  library: 'Library',
  remote: 'Remote',
  remoteEmptyBody: 'No series have been found. When searching for a specific series, try using a different name or provider.',
  remoteEmptyTitle: '何もない',
  remoteSeriesSummary: 'No summary is available for this series.',
  session: 'Session',
  sessionEmptyBody: 'No sessions have been found. When a chapter is being read, a session is created and will appear in this section.',
  sessionEmptyTitle: '何もない',
  sessionToastNextActive: 'Going to the next chapter!',
  sessionToastNextRepeat: 'Open the next chapter?',
  sessionToastNextUnavailable: 'No next chapter available.',
  sessionToastPreviousActive: 'Going to the previous chapter!',
  sessionToastPreviousRepeat: 'Open the previous chapter?',
  sessionToastPreviousUnavailable: 'No previous chapter available.'
};
