export const language = {
  basicConnectBody: 'Oops! The server is not supported. Check your device and server version, ensure both are up-to-date, and then try again.',
  basicConnectButtons: ['OK'],
  basicDisconnectBody: 'You are about to disconnect from the server. You will have to reenter connection and credential information to reconnect. Are you sure you wish to continue?',
  basicDisconnectButtons: ['Yes', 'No'],
  basicErrorBody: 'Oops! The server could not be reached or returned an error. Check your device and server connectivity, and then try again.',
  basicErrorButtons: ['Cancel', 'Retry'],
  basicIconBack: 'Back',
  basicIconClose: 'Close',
  basicIconSearch: 'Search',
  connect: 'Connect',
  connectPassword: 'Password',
  connectUsername: 'Username',
  connectServer: 'Server',
  library: 'Library',
  remote: 'Remote',
  remoteIconRefresh: 'Refresh',
  remoteEmptyBody: 'No series have been found. When searching for a specific series, try using a different name or provider.',
  remoteEmptyTitle: '何もない',
  remoteSeriesSummary: 'No summary is available for this series.',
  session: 'Session',
  sessionEmptyBody: 'No sessions have been found. When a chapter is being read, a session is created and will appear in this section.',
  sessionEmptyTitle: '何もない',
  sessionIconNextChapter: 'Next Chapter',
  sessionIconPreviousChapter: 'Previous Chapter',
  sessionIconRefresh: 'Refresh',
  sessionToastNextActive: 'Going to the next chapter!',
  sessionToastNextRepeat: 'Open the next chapter?',
  sessionToastNextUnavailable: 'No next chapter available.',
  sessionToastPreviousActive: 'Going to the previous chapter!',
  sessionToastPreviousRepeat: 'Open the previous chapter?',
  sessionToastPreviousUnavailable: 'No previous chapter available.'
};
