export const language = {
  basicConnectBody: 'The server version is not supported. Please update!',
  basicConnectButtons: ['OK'],
  basicDisconnectBody: 'You are about to disconnect from the server. Are you sure?',
  basicDisconnectButtons: ['Yes', 'No'],
  basicErrorBody: 'The server could not be reached or returned an error.',
  basicErrorButtons: ['Cancel', 'Retry'],
  basicIconBack: 'Back',
  basicIconClose: 'Close',
  basicIconSearch: 'Search',
  connect: 'Connect',
  connectPassword: 'Password',
  connectUsername: 'Username',
  connectServer: 'Server',
  library: 'Library',
  libraryEmptyBody: 'No series have been found. Series can be added to the library using the remote page. When searching, try using a different name.',
  libraryEmptyTitle: '何もない',
  remote: 'Remote',
  remoteIconRead: 'Read',
  remoteIconRefresh: 'Refresh',
  remoteEmptyBody: 'No series have been found. When searching for a specific series, try using a different name or provider.',
  remoteEmptyTitle: '何もない',
  remoteSeriesAbout: 'About',
  remoteSeriesChapters: 'Chapters',
  remoteSeriesSummary: 'No summary is available for this series.',
  session: 'Session',
  sessionEmptyBody: 'No sessions have been found. When a chapter is being read or synchronized, a session is created and will be listed here.',
  sessionEmptyTitle: '何もない',
  sessionIconNextChapter: 'Next Chapter',
  sessionIconPreviousChapter: 'Previous Chapter',
  sessionIconRefresh: 'Refresh',
  sessionToastNextActive: 'Going to the next chapter!',
  sessionToastNextRepeat: 'Open the next chapter?',
  sessionToastNextUnavailable: 'No next chapter available.',
  sessionToastPreviousActive: 'Going to the previous chapter!',
  sessionToastPreviousRepeat: 'Open the previous chapter?',
  sessionToastPreviousUnavailable: 'No previous chapter available.'
};
