import ArrowBackIos from '@material-ui/icons/ArrowBackIos';
import ChevronRight from '@material-ui/icons/ChevronRight';
import Close from '@material-ui/icons/Close';
import Folder from '@material-ui/icons/Folder';
import Home from '@material-ui/icons/Home';
import MoreVert from '@material-ui/icons/MoreVert';
import Public from '@material-ui/icons/Public';
import Refresh from '@material-ui/icons/Refresh';
import Search from '@material-ui/icons/Search';
export const icons = {ArrowBackIos, ChevronRight, Close, Folder, Home, MoreVert, Public, Refresh, Search};
