export const language = {
  remoteIconAdd: 'Add',
  remoteIconRead: 'Read',
  remoteEmpty: 'No series have been found. When searching for a specific series, try using a different name or provider.',
  remotePage: 'Page',
  remotePageNext: 'Next Page',
  remotePagePrevious: 'Previous Page',
  remoteSeriesAbout: 'About',
  remoteSeriesChapters: 'Chapters',
  remoteSeriesSummary: 'No summary is available for this series.',
  remoteSeriesInfoAuthor: 'Author',
  remoteSeriesInfoStatus: 'Status',
  remoteSeriesInfoStatusCompleted: 'Completed',
  remoteSeriesInfoStatusOngoing: 'Ongoing',
  remoteSeriesToastQuickRead: 'No chapter available.',
};
